name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            # Navigate to project folder
            cd /cipherFlow/Remote_Code_Executor/

            # Pull latest code
            git pull origin main

            # Install frontend dependencies and build
            cd ../client
            npm install
            npm run build

            # Copy frontend build to Nginx
            rm -rf /var/www/html/*
            cp -r build/* /var/www/html/

             # Install backend dependencies
            cd server
            npm install --production

            # Restart backend using pm2
            pm2 restart myapp || pm2 start npm --name "myapp" -- run start

            # Restart Nginx
            sudo nginx -t
            sudo systemctl restart nginx
